### ISSUE TITLE
add tgm activation

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/creativemag#31]
Add wp product review + tweet old post using tgm activation

**Comment by rodica-andronache** [comment]
@ineagu should we still work on this, or can I close it?

**Comment by ineagu** [comment]
close and remove theme

On Thu, Apr 7, 2016 at 1:56 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> should we still work on this, or can
> I close it?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/creativemag/issues/31#issuecomment-206811634>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
